
spring:
  data:
    redis:
      host: 172.29.190.31
      port: 6379
  # session登录态超时时间

  session:
    domain: 47.120.40.98
    timeout: 86400
    redis:
      save-mode: always

  application:
    name: lian-user-center

  datasource:
    url: jdbc:mysql://localhost:3306/user-center?serverTimezone=UTC
    username: lian
    password: ymy123456

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api

knife4j:
  enable: true
# 自动转换为驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    设置每次数据库查询更新操作会输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)